# Generated by Django 5.2.4 on 2025-10-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Vår'), ('summer', 'Sommer'), ('autumn', 'Høst'), ('winter', 'Vinter')], default='', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['season', 'month', 'day', 'name'],
            },
        ),
    ]
